name: Nilaway Action
description: Simple GitHub Action that detects potential Nil panics in Golang codebases
author: Qbaware
branding:
  icon: check-circle
  color: red

inputs:
  package-to-scan:
    description: Package to scan
    required: true
    default: "./..."

outputs:
  status:
    description: Whether potential Nil panics were found

runs:
  using: docker
  image: docker://ghcr.io/qbaware/nilaway-action:v0
  env:
    PACKAGE_TO_SCAN: ${{ inputs.package-to-scan }}
